### ISSUE TITLE
GitHub Flavoured Markdown now supports footnotes, too

### ISSUE THREAD

**Issue by ichard26** [hukkin/mdformat-gfm#21]
I just ran mdformat on my README for [diff-shades](https://github.com/ichard26/diff-shades) locally as a pre-commit hook and it behaved rather poorly on the footnotes I'm trying to add :slightly_frowning_face: A workaround is also install the `mdformat-myst` plugin alongside this one.

```diff
 ## License
 
@@ -333,12 +339,12 @@ black-primer and mypy-primer.
 
 First public release, enjoy the alpha quality software :)
 
+\[^1\]: I'll fix this with a hash based solution eventually, but for now let's
+be careful. \[^2\]: I know it’s specifically for Black, but diff-shades is a
+development tool for Black so I consider it acceptable - although I never asked
+… but then again, I am a maintainer of Black so yeah :p
+
 [black-primer]: https://github.com/psf/black/tree/main/src/black_primer
 [mypy-primer]: https://github.com/hauntsaninja/mypy_primer/
 [nox]: https://nox.thea.codes/en/stable/
 [pre-commit]: https://pre-commit.com/
-
-[^1]: I'll fix this with a hash based solution eventually, but for now let's be careful.
-[^2]: I know it’s specifically for Black, but diff-shades is a development tool for Black so I consider it acceptable - although I never asked … but then again, I am a maintainer of Black so yeah :p
```

https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/

---

Sorry for the minimal bug report but I am kinda busy on other stuff right now but I didn't want to forget filing an issue by pushing it off til I had more time. Feel free to ask for more details!

**Comment by ichard26** [comment]
post note: of course the GFM spec hasn't been updated to include footnotes, probably as wikis aren't supported yet if the rumours I've heard are true

**Comment by hukkin** [comment]
Thanks for the issue!

This is interesting. I'd argue that footnotes are *not* part of the GFM spec. The footnote extension is not now, nor has has it ever been described in the GFM text spec, see [rendered HTML](https://github.github.com/gfm/) or [source in VCS](https://github.com/github/cmark-gfm/blob/master/test/spec.txt).

My understanding is that an off-by-default footnote extension was added to cmark-gfm [a long time ago](https://github.com/github/cmark-gfm/pull/64) and was [recently enabled on github.com](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/). However, that doesn't make the extension part of the core specification IMO.

> A workaround is also install the mdformat-myst plugin alongside this one.

This should work, but so should `pip install mdformat-footnote` in case you don't want to enable all the other syntax extensions included in mdformat-myst.

**Comment by ichard26** [comment]
That's fair, I'll close this then and we can reopen if GitHub ever updates their formal specification for GFM.

> This should work, but so should `pip install mdformat-footnote` in case you don't want to enable all the other syntax extensions included in mdformat-myst.

Thanks!

**Comment by ichard26** [comment]
@Freed-Wu the [GFM specification hasn't been updated since 2019](https://github.github.com/gfm/) so no, mdformat-gfm won't be supporting it.
