### ISSUE TITLE
linkify vs GFM autolink

### ISSUE THREAD

**Issue by chrisjsewell** [hukkin/mdformat-gfm#22]
Heya @hukkin I was just looking at adding an option to myst-parser, for GM only parsing.
I think that linkify behaviour is not quite in strict adherence with https://github.github.com/gfm/#extended-email-autolink?
Is that correct and is there any linkify settings that could achieve this?

**Comment by hukkin** [comment]
Hey there!

> I think that linkify behaviour is not quite in strict adherence with https://github.github.com/gfm/#extended-email-autolink? Is that correct

Most likely that is correct. My understanding is that markdown-it's GFM related extensions are from a time before a formal GFM spec existed so I wouldn't be surprised if there are cases where the spec is not followed. That said, I'm not aware of any such cases.

> and is there any linkify settings that could achieve this?

I don't know.

**Comment by chrisjsewell** [comment]
Yeh no worries, just checking if it was something you had already considered
