### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by KyleKing** [hukkin/mdformat-gfm#31]
Can you please make a new release? This is the only remaining dependency for `mdformat-mkdocs` that pins `mdit-py-plugins` to `^0.3`, which is causing conflicts with `mdformat-frontmatter` which has recent fixes and a minimum of `0.4`

If helpful, I opened a PR with a patch for CI: #30 (to address https://github.com/hukkin/mdformat-gfm/pull/28#issuecomment-1694216314)

**Comment by kdeldycke** [comment]
Hey @hukkin , what's your opinion on granting @KyleKing maintainership of `mdformat-gfm`? He looks like a competent dev and is already managing a couple of `mdformat-*` plugins.

**Comment by KyleKing** [comment]
I'm happy to help as a maintainer!

**Comment by KyleKing** [comment]
The missing release has been a blocker, so I temporarily released mdformat-mkdocs (v2.0.1) with a copy of mdformat-gfm. Once the release of gfm is available, I can defer to this package and remove the copy

@hukkin, let me know if there is anything I can do help

**Comment by hukkin** [comment]
Hi all, I've made a release.

Thanks for offering to help Kyle! :bow:    I invited you as a collaborator. I hope you can give me a couple weeks to review changes and only merge without a review if I still remain absent.

**Comment by KyleKing** [comment]
Thanks! Let me know if there is anywhere else I can help
