### ISSUE TITLE
[Feature Request] Add support for alerts

### ISSUE THREAD

**Issue by timmens** [hukkin/mdformat-gfm#39]
GitHub has supported alerts since the end of 2023; see the community discussion [here](https://github.com/orgs/community/discussions/16925).

For example:

> [!NOTE]
> This is a note.

### Problem

Running `mdformat` (with `mdformat-gfm` installed) changes the correct syntax:

```markdown
> [!NOTE]
> This is a note.
```

to

```markdown
> \[!NOTE\] This is a note.
```

Which does not correctly render.

 ### Request
 
 Can this feature be supported? If not, is there some way to force the linter to ignore these cases?

**Comment by KyleKing** [comment]
I have a package to support GitHub alerts, 'mdformat-gfm-alerts'!

**Comment by timmens** [comment]
I can't believe I didn't find this earlier. This is amazing, and it works perfectly!
