### ISSUE TITLE
Alerts not supported

### ISSUE THREAD

**Issue by titusz** [hukkin/mdformat-gfm#40]
I noticed that the [alerts syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) is not supported.

This markdown:

```markdown
> [!CAUTION]
> This is an alert
```

will reformat/escape to:

```markdown
> \[!CAUTION\] This is an alert
```

which breaks the intended rendering:

> [!CAUTION]
>This is an alert

**Comment by KyleKing** [comment]
Hi @titusz, I have a package to support GitHub alerts, [mdformat-gfm-alerts](https://github.com/KyleKing/mdformat-gfm-alerts)!

Let me know if you run into any issues

**Comment by titusz** [comment]
Ah that´s perfect. Thanks!
